version: "3"

services:
  migrate:
    build: .
    command:
      - python
      - manage.py
      - migrate
    volumes:
      - ./db:/app/db
  web:
    build: .
    command:
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8000
    depends_on:
      - migrate
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
    environment:
      CELERY_BROKER_URL: 'redis://redishost:6379/0'
      GOOGLE_CLIENT_ID: '858644449172-nvvsa0mu677rg3a8fr9nsv1shk64re8u.apps.googleusercontent.com'
      GOOGLE_CLIENT_SECRET: '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'
      GITHUB_CLIENT_ID: '16226058214306527e19'
      GITHUB_CLIENT_SECRET: 'acd813b972ad12955fd863b39c6fca8e065bb53a'
  celery:
    build: .
    command:
      - celery
      - --app=user_login
      - worker
      - --loglevel=info
    depends_on:
      - migrate
    volumes:
      - ./db:/app/db
    environment:
      CELERY_BROKER_URL: 'redis://redishost:6379/0'
      EMAIL_HOST_USER: '0144melih@gmail.com' 
      EMAIL_HOST_PASSWORD: 'iqyb clut duhq sahb'
      DEFAULT_FROM_EMAIL: '0144melih@gmail.com'
  redis:
    hostname: redishost
    image: "redis:alpine"
