version: "3"

services:
  migrate:
    build: .
    command:
      - python
      - manage.py
      - migrate
    volumes:
      - ./db:/app/db
  web:
    build: .
    command:
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8000
    depends_on:
      - migrate
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
    environment:
      CELERY_BROKER_URL: 'redis://redishost:6379/0'
  celery:
    build: .
    command:
      - celery
      - --app=user_login
      - worker
      - --loglevel=info
    depends_on:
      - migrate
    volumes:
      - ./db:/app/db
    environment:
      CELERY_BROKER_URL: 'redis://redishost:6379/0'
  redis:
    hostname: redishost
    image: "redis:alpine"
